apiVersion: apps/v1
kind: Deployment
metadata:
  name: eisr-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eisr-mysql
  template:
    metadata:
      labels:
        app: eisr-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
          - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root123"
          - name: MYSQL_DATABASE
            value: "eisr_db"
          - name: MYSQL_USER
            value: "eisr_user"
          - name: MYSQL_PASSWORD
            value: "root123"
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
